services:
  wordpress:
    networks:
      - default
      - traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule: "Host(`${WP_HOST:?WP_HOST is required}`)"
      traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port: "8443"
      traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.scheme: https

networks:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK:-traefik}
